# Deny access to sensitive files
# /etc/nginx/snippets/deny-all.conf
# Nginx configuration snippet on r04
# generated: 2025-04-18
# Ansible managed, manual changes will be overwritten!

# Deny PHP execution in sensitive areas
# This denies access to PHP files in hidden directories
location ~ \..*/.*\.php$ {
    deny all;
}
# This denies access to the private directory under sites
location ~ ^/sites/[^/]+/private/ {
    deny all;
}
# Deny PHP execution in the files directory to prevent unauthorized script execution
location ~ ^/sites/[^/]+/files/.*\.php$ {
    deny all;
}
# Block access to the settings.php file, which often contains sensitive configuration
location ~* ^/sites/[^/]+/settings\.php$ {
    deny all;
}
# Deny PHP execution in the styles directory to prevent unauthorized script execution
location ~* ^/sites/[^/]+/files/styles/.*\.php$ {
    deny all;
}

# Block access to various sensitive file extensions and filenames
location ~* \.(engine|inc|install|make|module|profile|po|sh|sql|theme|twig|tpl|xtmpl|yml)(~|\.sw[op]|\.bak|\.orig|\.save)?$ {
    deny all;
}
location ~* ^/(README|CHANGELOG|LICENSE|COPYRIGHT|UPGRADE|INSTALL(?:.*\.txt)?)$ {
    deny all;
}
location ~* ^(\.(?!well-known)|Entries.*|Repository|Root|Tag|Template|composer\.(?:json|lock)|web\.config)$ {
    deny all;
}

# Deny access to sensitive file types and directories
location ~* \.(ini|conf|txt|log|git|env|DS_Store)$ {
    deny all;
}
location ~ /\.(htaccess|htpasswd)$ {
    deny all;
}
