# Deny access to sensitive files

# deny access to .htpasswd files
location ~ /\.htpasswd$ {
  deny all;
}

# deny access to .htaccess files
location ~ /\.htaccess$ {
  deny all;
}

# deny access to .git files
location ~ /\.git$ {
  deny all;
}

# deny access to .env files
location ~ /\.env$ {
  deny all;
}

# deny access to .DS_Store files
location ~ /\.DS_Store$ {
  deny all;
}
