# Deny access to sensitive files
# /etc/nginx/snippets/deny-all.conf
# Nginx configuration snippet on r04
# generated: 2025-04-18
# Ansible managed, manual changes will be overwritten!

location ~ /\.htpasswd$ {
  deny all;
}
location ~ /\.htaccess$ {
  deny all;
}
location ~ /\.git$ {
  deny all;
}
location ~ /\.env$ {
  deny all;
}
location ~ /\.DS_Store$ {
  deny all;
}