#######################################################
###  nginx.conf drupal config start
#######################################################

# Drupal 10+ configuration


#######################################################
###  nginx.conf drupal config end
#######################################################
