# /etc/nginx/snippets/drupal.conf
# Nginx drupal configuration file on r04
# generated: 2025-04-18
# Ansible managed, manual changes will be overwritten!

#######################################################
###  Common Nginx config for Drupal sites
#######################################################

autoindex            off;

#######################################################
### Drupal specific location rules adapted from
### https://www.nginx.com/resources/wiki/start/topics/recipes/drupal/
#######################################################

# Disable access and logging for favicon.ico
location = /favicon.ico {
  log_not_found off;
  access_log off;
}

# Disable access and logging for robots.txt
location = /robots.txt {
  allow all;
  log_not_found off;
  access_log off;
}

# Deny access to .txt and .log files
location ~* \.(txt|log)$ {
  deny all;
}

# Deny access to hidden files and directories
location ~ \..*/.*\.php$ {
  return 403;
}

# Deny access to private files
location ~ ^/sites/.*/private/ {
  return 403;
}

# Block access to PHP scripts in the files directory
location ~ ^/sites/[^/]+/files/.*\.php$ {
  deny all;
}

# Allow "Well-Known URIs" as per RFC 5785
location ~* ^/.well-known/ {
  allow all;
}

# Block access to "hidden" files and directories
location ~ (^|/)\. {
  return 403;
}

# Main location block
location / {
  try_files $uri /index.php?$query_string;
}

# Rewrite block for Drupal
location @rewrite {
  rewrite ^ /index.php;
}

# Don't allow direct access to PHP files in the vendor directory.
location ~ /vendor/.*\.php$ {
  deny all;
  return 404;
}

# Protect files and directories from prying eyes.
location ~* \.(engine|inc|install|make|module|profile|po|sh|.*sql|theme|twig|tpl(\.php)?|xtmpl|yml)(~|\.sw[op]|\.bak|\.orig|\.save)?$|^(\.(?!well-known).*|Entries.*|Repository|Root|Tag|Template|composer\.(json|lock)|web\.config)$|^#.*#$|\.php(~|\.sw[op]|\.bak|\.orig|\.save)$ {
  deny all;
  return 404;
}

# Route requests to FastCGI servers
location ~ \.php$|^/update.php {
  include snippets/fastcgi-php.conf;                                # Parameter passed to the FastCGI server
  include fastcgi_params;
  fastcgi_pass unix:/run/php/php8.3-fpm.sock;         # address of the FastCGI server, as unix socket path
  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # the script name to be executed by PHP
  fastcgi_param HTTP_PROXY      "";                                 # Block httpoxy attacks. See https://httpoxy.org/.
  fastcgi_param QUERY_STRING    $query_string;                      # pass request parameters to PHP
  fastcgi_intercept_errors      on;                                 # passing FastCGI server responses (300 or higher) to clients
}

# Static files
location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
  try_files $uri @rewrite;
  expires max;
  log_not_found off;
}

# Handle styles for Drupal
location ~ ^/sites/.*/files/styles/ {
  try_files $uri @rewrite;
}

# Handle private files, also with language prefix through Drupal.
location ~ ^(/[a-z\-]+)?/system/files/ {
  try_files $uri /index.php?$query_string;
}

# Enforce clean URLs - Could be done with 301 for permanent or other redirect codes.
if ($request_uri ~* "^(.*/)index\.php/(.*)") {
  return 307 $1$2;
}
#######################################################
###  common Nginx config for Drupal sites
#######################################################